apiVersion: v1
kind: ServiceAccount
metadata:
  name: admission-python

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-pod-reader
rules:
- apiGroups: [""]
  resources: ["nodes","nodes/status","nodes/metrics"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]


---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: get-nodes
subjects:
- kind: ServiceAccount
  name: admission-python # Name is case sensitive
  namespace: default
roleRef:
  kind: ClusterRole
  name: node-pod-reader
  apiGroup: rbac.authorization.k8s.io

