apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      initContainers:
        - name: check-db-ready
          image: postgres:9.6
          command: [ 'sh', '-c',
              'until pg_isready -h postgres -p 5432;
          do echo database is not ready; sleep 2; done;' ]
      containers:
        - name:  wordpress
          image:  wordpress:4.8-apache