apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: server-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: deployment
    name: server
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageValue: 50m
    - type: Resource
      resource:
        name: memory
        targetAverageValue: 200Mi
