kind: ConfigMap 
apiVersion: v1 
metadata:
  name: {{ .Values.configmap.name }} # myconfigmapv1.0
  namespace: {{ .Values.namespace }}
data:
  BG_COLOR: '#12181b'
  FONT_COLOR: '#FFFFFF'
  CUSTOM_HEADER: {{ .Values.configmap.data.CUSTOM_HEADER }} # 'Customized with a configmap!'
