---
apiVersion: v1
kind: Pod
metadata:
  name: poder
  labels:
    app: poder
spec:
  containers:
    - name: poder
      image: poder:v1.0

---
apiVersion: v1
kind: Service
metadata:
  name: poder
spec:
  selector:
    app: poder
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080