apiVersion: v1
kind: Pod
metadata:
  name: dataaccess
spec:
  containers:
  - name: alpine
    image: alpine:latest
    command: ['sleep', 'infinity']
    volumeMounts:
    - name: db-volume
      mountPath: /data
  volumes:
    - name: db-volume
      persistentVolumeClaim:
        claimName: pvc-small